# kivy 1.11.1
#Kv do exercicio_1_kv

<MainLayoutGrid>:

    cols: 3


    Button:
        text: 'Button 1'
    Button:
        text: 'Button 2'
    Button:
        text: 'Button 3'
    Button:
        text: 'Button 4'
    Button:
        text: 'Button 5'
    Button:
        text: 'Button 6'
    Button:
        text: 'Button 7'
    Button:
        text: 'Button 8'
    Button:
        text: 'Button 9'
